// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odiuvtcpxdwtihwyosnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kaXV2dGNweGR3dGlod3lvc25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODIwOTksImV4cCI6MjA2MDM1ODA5OX0.SxpEIkbTl0l2xanG6X56EFvfPHq30ohXumI_Kawjk9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);